
name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql_version: ["5.7", "8.0"]
    services:
      mysql:
        image: mysql:${{ matrix.mysql_version }}
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "test"
          TZ: America/Los_Angeles
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Build
      run: script/cibuild
    - name: Upload gh-ost binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: gh-ost
        path: bin/gh-ost
